server {
    listen 80;
    listen [::]:80;
    server_name treinamentos.aquafast.com.br;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name treinamentos.aquafast.com.br;

    root /var/www/aquafast-treina/current/public;
    index index.php;
    client_max_body_size 21m;

    ssl_certificate /etc/letsencrypt/live/treinamentos.aquafast.com.br/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/treinamentos.aquafast.com.br/privkey.pem;

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.3-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
        fastcgi_param HTTPS on;
    }

    location ~ /\. {
        deny all;
    }

    location ~* /(storage/app|\.env|composer\.(json|lock)|package(-lock)?\.json)$ {
        deny all;
    }
}
